export default {
    PRODUCT_FETCHED: 'PRODUCT_FETCHED',
    PRODUCTS_FETCHED: 'PRODUCTS_FETCHED',

    CATALOG_INDICATOR_UPDATED: 'CATALOG_INDICATOR_UPDATED',
    CATALOG_SOLD_INDICATOR: 'CATALOG_SOLD_INDICATOR',
    CATALOG_NEW_INDICATOR: 'CATALOG_NEW_INDICATOR',
    CATALOG_DELIVERED_INDICATOR: 'CATALOG_DELIVERED_INDICATOR',
    CATALOG_APPROVED_INDICATOR: 'CATALOG_APPROVED_INDICATOR',
    PRODUCTS_TOP_SELLING: 'PRODUCTS_TOP_SELLING'
}
