export default {
    AUTH_USER_WAS_SIGNED_IN: 'AUTH_USER_WAS_SIGNED_IN',
    AUTH_USER_SIGNED_IN_ROLE_WAS_SETTED: 'AUTH_USER_SIGNED_IN_ROLE_WAS_SETTED',
    AUTH_USER_WAS_SIGNED_OUT: 'AUTH_USER_WAS_SIGNED_OUT',
    AUTH_SET_USER_FROM_SESSION: 'AUTH_SET_USER_FROM_SESSION',
    AUTH_USER_SESSION_KEY_WAS_CLEAR: 'AUTH_USER_SESSION_KEY_WAS_CLEAR'
}
