export default {

    /* HOME PAGE INDICATORS */
    HOME_MANAGER_INDICATOR_UPDATED: 'HOME_MANAGER_INDICATOR_UPDATED',
    HOME_ADMIN_INDICATOR_UPDATED: 'HOME_ADMIN_INDICATOR_UPDATED',

    /* ADMIN */
    ADMIN_CATALOG_INDICATOR: 'ADMIN_CATALOG_INDICATOR',
    ADMIN_PRICED_INDICATOR: 'ADMIN_PRICED_INDICATOR',
    ADMIN_BILLED_INDICATOR: 'ADMIN_BILLED_INDICATOR',
    ADMIN_ORDER_INDICATOR: 'ADMIN_ORDER_INDICATOR',
    ADMIN_MARKUP_INDICATOR: 'ADMIN_MARKUP_INDICATOR',
    ADMIN_INVOICED_INDICATOR: 'ADMIN_INVOICED_INDICATOR',
    ADMIN_RECIPE_INDICATOR: 'ADMIN_RECIPE_INDICATOR',
    ADMIN_EXPENSES_INDICATOR: 'ADMIN_EXPENSES_INDICATOR',
    ADMIN_SELLERS_INDICATOR: 'ADMIN_SELLERS_INDICATOR',
    ADMIN_ORDERS_CANCELED_INDICATOR: 'ADMIN_ORDERS_CANCELED_INDICATOR',
    ADMIN_ORDERS_DELIVERED_INDICATOR: 'ADMIN_ORDERS_DELIVERED_INDICATOR',
    ADMIN_ORDERS_LATE_INDICATOR: 'ADMIN_ORDERS_LATE_INDICATOR',
    ADMIN_ORDERS_NEW_INDICATOR: 'ADMIN_ORDERS_NEW_INDICATOR',
    ADMIN_ORDERS_PENDING_INDICATOR: 'ADMIN_ORDERS_PENDING_INDICATOR',
    ADMIN_TRANSPORT_SHIPPED_INDICATOR: 'ADMIN_TRANSPORT_SHIPPED_INDICATOR',
    ADMIN_TRANSPORT_ORIGIN_INDICATOR: 'ADMIN_TRANSPORT_ORIGIN_INDICATOR',
    ADMIN_TRANSPORT_RECEIVER_INDICATOR: 'ADMIN_TRANSPORT_RECEIVER_INDICATOR',
    ADMIN_TRANSPORT_IN_TRANSPORT_INDICATOR: 'ADMIN_TRANSPORT_IN_TRANSPOR_INDICATOR',
    ADMIN_TRANSPORT_DELIVERED_INDICATOR: 'ADMIN_TRANSPORT_DELIVERED_INDICATOR',

    /* Indicators */
    CATALOG_INDICATOR: 'UPDATE_CATALOG_INDICATOR',
    PRICED_INDICATOR: 'UPDATE_PRICED_INDICATOR',
    BILLED_INDICATOR: 'UPDATE_BILLED_INDICATOR',
    ORDER_INDICATOR: 'UPDATE_ORDER_INDICATOR',
    MARKUP_INDICATOR: 'UPDATE_MARKUP_INDICATOR',

    /* CATALOG PAGE INDICATORS */

    /* ORDERS PAGE INDICATORS */
    ORDERS_INDICATOR_UPDATED: 'ORDERS_INDICATOR_UPDATED',
    /* Indicators */
    ORDERS_CANCELED_INDICATOR: 'ORDERS_CANCELED_INDICATOR',
    ORDERS_DELIVERED_INDICATOR: 'ORDERS_DELIVERED_INDICATOR',
    ORDERS_LATE_INDICATOR: 'ORDERS_LATE_INDICATOR',
    ORDERS_NEW_INDICATOR: 'ORDERS_NEW_INDICATOR',
    ORDERS_PENDING_INDICATOR: 'ORDERS_PENDING_INDICATOR',


    /* LOGISTICS PAGE INDICATORS */
    LOGISTICS_INDICATOR_UPDATED: 'LOGISTICS_INDICATOR_UPDATED',
    /* Indicators */
    LOGISTICS_DELIVERED_INDICATOR: 'LOGISTICS_DELIVERED_INDICATOR',
    LOGISTICS_NEW_INDICATOR: 'LOGISTICS_NEW_INDICATOR',
    LOGISTICS_LATE_INDICATOR: 'LOGISTICS_LATE_INDICATOR',
    LOGISTICS_TRANSPORT_SHIPPED_INDICATOR: 'LOGISTICS_TRANSPORT_SHIPPED_INDICATOR',
    LOGISTICS_TRANSPORT_ORIGIN_INDICATOR: 'LOGISTICS_TRANSPORT_ORIGIN_INDICATOR',
    LOGISTICS_TRANSPORT_RECEIVER_INDICATOR: 'LOGISTICS_TRANSPORT_RECEIVER_INDICATOR',
    LOGISTICS_TRANSPORT_IN_TRANSPORT_INDICATOR: 'LOGISTICS_TRANSPORT_IN_TRANSPOR_INDICATOR',
    LOGISTICS_TRANSPORT_DELIVERED_INDICATOR: 'LOGISTICS_TRANSPORT_DELIVERED_INDICATOR',

    /* Collections */
    ALL_TOP_SELLING_FETCHED: 'ALL_TOP_SELLING_FETCHED',
    MY_TOP_SELLING_FETCHED: 'MY_TOP_SELLING_FETCHED',

    ORDERS_FETCHED: 'ORDERS_FETCHED',


    LOGISTICS_FETCHED: 'LOGISTICS_FETCHED'

}
