import { ADMIN_ROLE, MANAGER_ROLE, GUEST_ROLE } from 'constants'
const FOR_ALL = [ADMIN_ROLE, MANAGER_ROLE, GUEST_ROLE]

export default {
    "dashboard_admin_index":{
        "label":"Dashboard !A",
        "route":"/dashboard/admin",
        "href":"/dashboard/admin",
        "page":"dashboard-home-admin",
        "menu":true,
        "icon":"dashboard",
        "child":false,
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default",

    },
    "dashboard_manager_index":{
        "label":"Dashboard !M",
        "route":"/dashboard/manager",
        "href":"/dashboard/manager",
        "page":"dashboard-home-manager",
        "menu":false,
        "icon":"dashboard",
        "child":false,
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "sellers_index":{
        "label":"Lojístas",
        "route":"/sellers/index",
        "href":"/sellers/index",
        "page":"sellers",
        "menu":true,
        "icon":"star-o",
        "child":false,
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "sellers_view":{
        "label":"Informações do lojísta",
        "route":"/sellers/view/:id",
        "href":"/sellers/view/",
        "page":"sellers",
        "menu":false,
        "child":[
            "sellers_index"
        ],
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "sellers_edit":{
        "label":"Editar cadastro do lojísta",
        "route":"/sellers/edit/:id",
        "href":"/sellers/edit/",
        "page":"sellers",
        "menu":false,
        "child":[
            "sellers_index",
            "sellers_view"
        ],
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "sellers_register":{
        "label":"Cadastrar lojísta",
        "route":"/sellers/register",
        "href":"/sellers/register",
        "page":"sellers",
        "menu":false,
        "child":[
            "sellers_index"
        ],
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "support_index":{
        "label":"Atendimento",
        "route":"/support/index",
        "href":"/support/index",
        "menu":true,
        "page":"support",
        "icon":"ambulance",
        "child":false,
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "support_view":{
        "label":"Dados do chamado",
        "route":"/support/view/:id",
        "href":"/support/view/",
        "menu":false,
        "page":"support",
        "child":[
            "support_index"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "support_edit":{
        "label":"Editar chamado",
        "route":"/support/edit/:id",
        "href":"/support/edit/",
        "menu":false,
        "page":"support",
        "child":[
            "support_index",
            "support_view"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "support_register":{
        "label":"Abrir chamado",
        "route":"/support/register",
        "href":"/support/register",
        "menu":false,
        "page":"support",
        "child":[
            "support_index"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "support_user_guide":{
        "label":"Manual",
        "route":"/support/user-guide",
        "href":"/support/user-guide",
        "menu":false,
        "page":"support",
        "child":false,
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "faq_index":{
        "label":"Dúvidas frequentes",
        "route":"/faq/index",
        "href":"/faq/index",
        "menu":true,
        "page":"faq",
        "icon":"question-circle",
        "child":false,
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "faq_view":{
        "label":"Pergunta frequente",
        "route":"/faq/view/:id",
        "href":"/faq/view/",
        "menu":false,
        "page":"faq",
        "child":[
            "faq_index"
        ],
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "faq_edit":{
        "label":"Editar dúvida frequente",
        "route":"/faq/edit/:id",
        "href":"/faq/edit/",
        "menu":false,
        "page":"faq",
        "child":[
            "faq_index",
            "faq_view"
        ],
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "faq_register":{
        "label":"Adicionar dúvida frequente",
        "route":"/faq/register",
        "href":"/faq/register",
        "menu":false,
        "page":"faq",
        "child":[
            "faq_index"
        ],
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "devices_index":{
        "label":"Dispositivos",
        "route":"/devices/index",
        "href":"/devices/index",
        "menu":true,
        "page":"devices",
        "icon":"cube",
        "child":false,
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "devices_view":{
        "label":"Informações do dispositivo",
        "route":"/devices/view/:id",
        "href":"/devices/view/",
        "menu":false,
        "page":"devices",
        "child":[
            "devices_index"
        ],
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "devices_edit":{
        "label":"Editar informações do dispositivo",
        "route":"/devices/edit/:id",
        "href":"/devices/edit/",
        "menu":false,
        "page":"devices",
        "child":[
            "devices_index",
            "devices_view"
        ],
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "devices_register":{
        "label":"registrar dispositivo",
        "route":"/devices/register",
        "href":"/devices/register",
        "menu":false,
        "page":"devices",
        "child":[
            "devices_index"
        ],
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "auth_sign_in":{
        "slug":"auth_sign_in",
        "label":"Entrar",
        "route":"/",
        "href":"/sign-in",
        "menu":false,
        "child":false,
        "roles":[
            GUEST_ROLE
        ],
        "template":"default"
    },
    "auth_unauthorized":{
        "label":"Sem autorização de acesso",
        "route":"/you-shall-not-pass",
        "href":"/you-shall-not-pass",
        "menu":false,
        "child":false,
        "roles":FOR_ALL,
        "template":"default"
    },
    "auth_contract":{
        "label":"Contrato",
        "route":"/contract",
        "href":"/contract",
        "menu":false,
        "child":false,
        "roles":[
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "auth_register":{
        "label":'Cadastro de usuário',
        "route":"/register",
        "href":"/register",
        "menu":false,
        "child":false,
        "roles":[
            GUEST_ROLE
        ],
        "template":"default"
    },
    "auth_sign_out":{
        "label":'Encerrar sessão',
        "route":"/log-out",
        "href":"/log-out",
        "menu":false,
        "child":false,
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "settings_seller_ui":{
        "label":"Personalização da loja",
        "route":"/settings/seller/ui/:id",
        "href":"/settings/seller/ui/",
        "menu":false,
        "page":"settings",
        "icon":"cogs",
        "child":false,
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "settings_index":{
        "label":"Configurações",
        "route":"/settings/index",
        "href":"/settings/index",
        "menu":false,
        "page":"settings",
        "child":false,
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "products_index":{
        "label":"Catálogo",
        "route":"/products/index",
        "href":"/products/index",
        "menu":true,
        "page":"products",
        "icon":"book",
        "child":false,
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "products_view":{
        "label":"Dados do produto",
        "route":"/products/view/:id",
        "href":"/products/view/",
        "page":"products",
        "menu":false,
        "child":[
            "products_index"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "products_edit":{
        "label":"Editar informações do produto",
        "route":"/products/edit/:id",
        "href":"/products/edit/",
        "page":"products",
        "menu":false,
        "child":[
            "products_index",
            "products_view"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "products_register":{
        "label":"Novo produto",
        "route":"/products/register",
        "href":"/products/register",
        "page":"products",
        "menu":false,
        "child":[
            "products_index"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "users_index":{
        "label":"Usuários",
        "route":"/users/index",
        "href":"/users/index",
        "menu":true,
        "page":"users",
        "icon":"users",
        "child":false,
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "users_view":{
        "label":"Informações do usuário",
        "route":"/users/view/:id",
        "href":"/users/view/",
        "page":"users",
        "menu":false,
        "child":[
            "users_index"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "users_edit":{
        "label":"Editar informações do usuário",
        "route":"/users/edit/:id",
        "href":"/users/edit/",
        "page":"users",
        "menu":false,
        "child":[
            "users_index",
            "users_view"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "users_register":{
        "label":"Registrar usuário",
        "route":"/users/register",
        "href":"/users/register",
        "page":"users",
        "menu":false,
        "child":[
            "users_index"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "finances_index":{
        "label":"Financeiro",
        "route":"/finances/index",
        "href":"/finances/index",
        "menu":true,
        "page":"finances",
        "icon":"dollar",
        "child":false,
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "finances_view":{
        "label":"Informações do registro financeiro",
        "route":"/finances/view/:id",
        "href":"/finances/view/",
        "menu":false,
        "page":"finances",
        "child":[
            "finances_index"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "finances_edit":{
        "label":"Revisar informações do registro financeiro",
        "route":"/finances/edit/:id",
        "href":"/finances/edit/",
        "menu":false,
        "page":"finances",
        "child":[
            "finances_index",
            "finances_view"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "finances_register":{
        "label":"Novo registro financeiro",
        "route":"/finances/register",
        "href":"/finances/register",
        "menu":false,
        "page":"finances",
        "child":[
            "finances_index"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "campaigns_index":{
        "label":"Campanhas",
        "route":"/campaigns/index",
        "href":"/campaigns/index",
        "menu":true,
        "page":"campaigns",
        "icon":"suitcase",
        "child":false,
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "campaigns_view":{
        "label":"Dashboard da campanha",
        "route":"/campaigns/view/:id",
        "href":"/campaigns/view/",
        "menu":false,
        "page":"campaigns",
        "child":[
            "campaigns_index"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "campaigns_edit":{
        "label":"Revisar informações campanha",
        "route":"/campaigns/edit/:id",
        "href":"/campaigns/edit/",
        "menu":false,
        "page":"campaigns",
        "child":[
            "campaigns_index",
            "campaigns_view"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "campaigns_register":{
        "label":"Criar campanha",
        "route":"/campaigns/register",
        "href":"/campaigns/register",
        "menu":false,
        "page":"campaigns",
        "child":[
            "campaigns_index"
        ],
        "roles":[
            ADMIN_ROLE,
            MANAGER_ROLE
        ],
        "template":"default"
    },
    "logistics_index":{
        "label":"Logística",
        "route":"/logistics/index",
        "href":"/logistics/index",
        "page":"logistics",
        "menu":true,
        "icon":"star-o",
        "child":false,
        "roles":[
            ADMIN_ROLE
        ],
        "template":"default"
    },
    "logistics_view":{
        "label":"Informações",
        "route":"/logistics/view/:id",
        "href":"/logistics/view/",
        "page":"logistics",
        "menu":false,
        "child":[
            "logistics_index"
        ],
        "roles":[
            ADMIN_ROLE
        ]
    },



    "mail_index":{
        "label":"Caixa de entrada",
        "route":"/mail/index",
        "href":"/mail/index",
        "menu":true,
        "page":"mail",
        "icon":"question-circle",
        "child":false,
        "roles":[
            ADMIN_ROLE, MANAGER_ROLE
        ],
        "template":"default"
    },
    "mail_view":{
        "label":"Notificação",
        "route":"/mail/view/:id",
        "href":"/mail/view/",
        "menu":false,
        "page":"mail",
        "child":[
            "mail_index"
        ],
        "roles":[
            ADMIN_ROLE, MANAGER_ROLE
        ],
        "template":"default"
    },
    "mail_edit":{
        "label":"Editar notificação",
        "route":"/mail/edit/:id",
        "href":"/mail/edit/",
        "menu":false,
        "page":"mail",
        "child":[
            "mail_index",
            "mail_view"
        ],
        "roles":[
            ADMIN_ROLE, MANAGER_ROLE
        ],
        "template":"default"
    },
    "mail_register":{
        "label":"Escrever",
        "route":"/mail/register",
        "href":"/mail/register",
        "menu":false,
        "page":"mail",
        "child":[
            "mail_index"
        ],
        "roles":[
            ADMIN_ROLE, MANAGER_ROLE
        ],
        "template":"default"
    }
}
