export default {
    FINANCE_FETCHED: 'FINANCE_FETCHED',
    FINANCES_FETCHED: 'FINANCES_FETCHED',

    FINANCES_INDICATOR_UPDATED: 'FINANCES_INDICATOR_UPDATED',
    FINANCES_PROFIT_INDICATOR: 'FINANCES_PROFIT_INDICATOR'
}
