export default {
    SELLER_FETCHED: 'SELLER_FETCHED',
    SELLERS_FETCHED: 'SELLERS_FETCHED',
    SELLERS_INDICATOR_UPDATED: 'SELLERS_INDICATOR_UPDATED',
    SELLERS_TOP_INDICATOR: 'SELLERS_TOP_INDICATOR',
    SELLER_KEY_ACCOUNT_FETCHED: 'SELLER_KEY_ACCOUNT_FETCHED'
}
